name: Sincronizador Automatizado de APIs

on:
  schedule:
    - cron: '0 */3 * * *' # Roda automaticamente a cada 3 horas
  workflow_dispatch: # Permite rodar manualmente clicando no botão

# Força o ambiente do GitHub Actions a usar a engine do Node 24 para as ações nativas
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  coletar-e-commitar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Atualizado para a versão estável atual LTS

      - name: Executar Script de Coleta
        run: node fetch-data.js

      - name: Commitar alterações do JSON
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          mkdir -p public
          git add public/data.json
          
          git diff-index --quiet HEAD || git commit -m "chore: cotações atualizadas [skip ci]"
          git push
